FROM registry.cn-zhangjiakou.aliyuncs.com/xuelingkang/library/oracle-jdk:8u261

MAINTAINER xuelingkang

COPY aspectjweaver-1.9.6.jar /aspectjweaver.jar

ENV ASPECTJ_VERSION=1.9.6

# docker build -t registry.cn-zhangjiakou.aliyuncs.com/xuelingkang/library/oracle-jdk-aspectj:8u261 .
# docker push registry.cn-zhangjiakou.aliyuncs.com/xuelingkang/library/oracle-jdk-aspectj:8u261
