FROM scratch

MAINTAINER xuelingkang

COPY aspectjweaver-1.9.6.jar /aspectjweaver.jar

# docker build -t registry.cn-zhangjiakou.aliyuncs.com/xzixi/aspectjweaver:1.9.6 .
# docker push registry.cn-zhangjiakou.aliyuncs.com/xzixi/aspectjweaver:1.9.6
