version: '3'

services:
  mysql:
    image: mysql:8.0.21
    container_name: portal_mysql
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/initdb.d/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin

  redis:
    image: redis:6.0.6
    container_name: portal_redis
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass portal

  rabbitmq:
    image: rabbitmq:3.8.7-management
    container_name: portal_rabbitmq
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      - RABBITMQ_DEFAULT_USER=portal
      - RABBITMQ_DEFAULT_PASS=portal
    ports:
      - "5672:5672"
      - "15672:15672"

  elasticsearch:
    image: elasticsearch:6.8.10
    container_name: portal_es
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/plugins/ik/:/etc/elasticsearch/plugins/ik/
    environment:
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:6.8.10
    container_name: portal_kibana
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - "elasticsearch"

  nacos:
    image: nacos/nacos-server:1.3.1
    container_name: portal_nacos
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      - MODE=standalone
      - PREFER_HOST_MODE=hostname
      - NACOS_AUTH_ENABLE=true
    ports:
      - "8848:8848"

  file:
    image: registry.cn-zhangjiakou.aliyuncs.com/publicx/sshd:7.9p1
    container_name: portal_file
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    environment:
      - SSH_USER=portalfile
      - SSH_PWD=portal
    ports:
      - "122:22"

networks:
  default:
    name: portal_dev
