# 开发环境
spring:
  # 数据源
  datasource:
    url: jdbc:mysql://docker:3306/portal?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    druid:
      initial-size: 5  # 初始化大小
      min-idle: 5  # 最小
      max-active: 10  # 最大
      max-wait: 60000  # 连接超时时间
      pool-prepared-statements: true # 打开PSCache
      max-pool-prepared-statement-per-connection-size: 20 # 指定每个连接上的PSCache大小

  # redis
  redis:
    host: docker # 默认localhost
    port: 6379 # 默认6379
    password: portal # 密码
    database: 1 # 采用哪个数据库，默认0
    timeout: 500 # 连接超时时间（毫秒）
    lettuce:
      shutdown-timeout: 100ms
      pool:
        max-active: 8 # 连接池最大连接数,默认8个，（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 1 # 连接池中的最小空闲连接

  # rabbitmq
  rabbitmq:
    host: docker
    port: 5672
    username: portal
    password: portal

  # 邮件
  mail:
    username: xxxxxx@163.com
    password: xxxxxx

  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: docker:9300
      repositories:
        enabled: true

# sftp
sftp-pool:
  # 主机ip
  host: docker
  # 端口号
  port: 22
  # 用户名
  username: portalfile
  # 密码
  password: portal

server:
  port: 8080
  jetty:
    accesslog:
      enabled: true # 开启访问日志，默认false

log:
  home: E:/project/java/logs/self-portal # 日志目录

attachment:
  save-dir: /home/portalfile # 文件保存路径

swagger2:
  enable: true # 启用swagger2

reset-password-url: http://localhost:3000/reset-password.html
